### PR TITLE
add weight engine (#1105)

### PR DESCRIPTION
**Pull request by kmaehashi**
This implements a feature to test fv_converter behavior (#1105)

### CODE REVIEW

**Comment by kmaehashi** [comment]
This PR depends on core weight module: https://github.com/jubatus/jubatus_core/pull/288

**Comment by kmaehashi** [comment]
In the initial issue (#1105) I proposed the following RPC signatures:

```
map<string,float> update(datum d);
map<string,float> calc_weight(datum d);
```

... however this PR uses:

```
message feature {
  0: string key
  1: float  value
}

list<feature> update(datum d);
list<feature> calc_weight(datum d);
```

This is intentionally changed to it keep the order of feature vector dimensions so that it is easier to understand.

**Comment by rimms** [comment]
LGTM 👍 
I will merge this PR after https://github.com/jubatus/jubatus_core/pull/288.

**Comment by kmaehashi** [comment]
Directly fixed indent of IDL in da6138349b56430687d39e66eda52856a3d7fc87 to avoid CI errors.

http://ci.jubat.us/job/website/Branch=develop/31/console#footer

**Pull request merged**
