### PR TITLE
Install python bridge in DEB/RPM packages

### LINKED ISSUE #1210: Image feature plug-in was not available in RHEL 6
Although we fixed image feature plug-in to support OpenCV 2.0 (https://github.com/jubatus/jubatus/pull/1174), we haven't provide RPM package for it...

### PR DESCRIPTION
**Pull request by kmaehashi**
Related to and depends on #1208

This PR also fixes #1210.

### CODE REVIEW

**Comment by kmaehashi** [comment]
I confirmed that packages can be built with Ubuntu 12.04/14.04/16.04 and RHEL 7.
The default python package provided in RHEL 6 does not provide `python.pc`, which is required to link python shared library. So we don't support this plug-in in RHEL 6.

**Comment by kmaehashi** [comment]
rebased to the latest develop branch.

**Comment by kmaehashi** [comment]
You need to rebuild packaging docker images.

**Comment by rimms** [comment]
Great works!! 👍 

I tested on all distribution using docker (Ubuntu {12, 14, 16} and RHEL {6, 7}).

**Pull request merged**
