### PR TITLE
Improve get_status of anomaly

### LINKED ISSUE #1194: Improve get_status of anomaly
This issue is a part of #633 .

``jubaanomaly::get_status()`` returns only the type of storage like ``{"storage": "lof"}``.

I picked up some useful metrics of ``jubaanomaly``.

How about my idea?

* lof and light_lof
  * ``max_id``: current max value of id in storage (useful to understand next id)
  * ``num_ignored``: the number of ids that were ignored by ``ignore_kth_same_point`` 
  * unlearner's status: See https://github.com/jubatus/jubatus_core/pull/166
* lof
  * ``num_id_master``: number of ids in ``lof_storage::_lof_table``
  * ``num_id_diff``: number of ids in ``lof_storage::_lof_table_diff``
* light_lof
  * ``num_id``: number of ids (we can get this via ``len(get_all_ids())``)

### PR DESCRIPTION
**Pull request by rimms**
Fixes #1194 

This patch should be merged after https://github.com/jubatus/jubatus_core/pull/372.

### CODE REVIEW

**Comment by TkrUdagawa** [comment]
Is it OK that num_id become less than num_unlearner_id after mix.
Full config and scripts are [here](https://gist.github.com/TkrUdagawa/2f780f02973c994c048a7739828cbb4f).

I'm testing the situation below
- jubaanomaly_proxy (running on port 9199)
- jubaanomaly (running on port 19199)
- jubaanomaly (running on port 19200)
light_lof with random unlearner (max_size = 15)

And I did below:

1. add 10 data
2. print status
3. do mix
4. print status
5. add more 10 data
6. print status
7. do mix
8. print status

The result was
```
1. add 10 data

2. status before mix
19199
    num_id:3
    num_unlearner_ids:3
19200
    num_id:8
    num_unlearner_ids:8

3. do mix

4. status after mix
19199
    num_id:10
    num_unlearner_ids:10
19200
    num_id:10
    num_unlearner_ids:10

5. add more 10 data

6. status before mix
19199
    num_id:15
    num_unlearner_ids:15
19200
    num_id:15
    num_unlearner_ids:15

7. do mix

8. status after mix
19199
    num_id:10 <- num_id become less than num_unlearner_ids
    num_unlearner_ids:15
19200
    num_id:11
    num_unlearner_ids:15
```

**Comment by rimms** [comment]
Ummm. I think this problem is the bug of light_lof with unlearner.
Because ``get_all_rows`` returns the same value of ``num_id``.

We should solve this problem. I raised new issue. https://github.com/jubatus/jubatus/issues/1204

**Comment by TkrUdagawa** [comment]
I see that this problem is caused by light_lof implementation and get_status works correctly.
We will merge this PR but continue the discussion in #1204.

**Comment by TkrUdagawa** [comment]
Thanks!

**Pull request merged**
