### PR TITLE
Revert "use same storage class for standalone and distributed mode (fix #469)"

### LINKED ISSUE #469: Model compatibility in classifiers
Classifier models for stand alone mode are incompatible with models for distributed mode. It is because they use different storage classes, `local_storage` and `local_storage_mixture`.

### PR DESCRIPTION
**Pull request by kmaehashi**
This reverts commit 26362610725c42190b7dbcd2fb3377d467424fee. Refs #1190

### CODE REVIEW

**Comment by kmaehashi** [comment]
This PR must be merged after https://github.com/jubatus/jubatus_core/pull/359.

I run benchmarks over these patches and confirmed the improvement, using News20 jubatus-tutorial-python example (``time python tutorial.py > /dev/null``).

### Before: using local_storage_mixture (Jubatus 1.0.2), via RPC

Average runtime: 49.721 sec.

```
python tutorial.py > /dev/null  9.86s user 2.40s system 24% cpu 49.586 total
python tutorial.py > /dev/null  9.80s user 2.37s system 24% cpu 50.215 total
python tutorial.py > /dev/null  9.43s user 2.49s system 24% cpu 49.362 total
```

### After: using local_storage (#1193 + https://github.com/jubatus/jubatus_core/issues/359), via RPC

Average runtime: 41.975 sec.

```
python tutorial.py > /dev/null  9.80s user 2.34s system 29% cpu 41.746 total
python tutorial.py > /dev/null  9.82s user 2.35s system 28% cpu 42.269 total
python tutorial.py > /dev/null  9.52s user 2.49s system 28% cpu 41.910 total
```

**Comment by kmaehashi** [comment]
The only downside of this PR spec is that feature vectors which are not MIXed yet are ignored in standalone mode when loading models generated in distributed mode.  When you are trying to migrate from distributed to standalone, you need to save model after doing MIX.

**Comment by shiodat** [comment]
:100: 

I also tested with [this script](https://gist.github.com/shiodat/99470184ac92a3c42c8a88b29b2ef06d) and confirmed the improvement with these patches.

#### Before: using local_storage_mixture (Jubatus 1.0.2), via RPC and Embedded
```
$ python benchmark.py  
[server] batch_size: 1, train_time: 27.2937[s]
[server] batch_size: 10, train_time: 20.1504[s]
[server] batch_size: 100, train_time: 18.9459[s]
[embedded] batch_size: 1, train_time: 18.7774[s]
[embedded] batch_size: 10, train_time: 18.7828[s]
[embedded] batch_size: 100, train_time: 18.5782[s]
```

#### After: using local_storage (#1193 + jubatus/jubatus_core#359), via RPC and Embedded
```
$ python benchmark.py
[server] batch_size: 1, train_time: 22.8101[s]
[server] batch_size: 10, train_time: 15.9985[s]
[server] batch_size: 100, train_time: 14.6249[s]
[embedded] batch_size: 1, train_time: 14.3755[s]
[embedded] batch_size: 10, train_time: 12.8956[s]
[embedded] batch_size: 100, train_time: 13.1598[s]
```

We have to announce the downside of this PR by website and blog.

**Comment by kmaehashi** [comment]
> The only downside of this PR spec is that feature vectors which are not MIXed yet are ignored in standalone mode when loading models generated in distributed mode. When you are trying to migrate from distributed to standalone, you need to save model after doing MIX.

Ah, one more thing to note: when loading models saved in standalone mode of Jubatus 1.0.0-1.0.2 to Jubatus 1.0.3, it behaves as if they are saved in distributed mode, as 1.0.0-1.0.2 is using ``local_storage_mixture``.

**Comment by kmaehashi** [comment]
Refs #1153

**Pull request merged**
