### PR TITLE
escape from Google Code (fix #980)

### LINKED ISSUE #980: Escape from Google Code
Related to https://github.com/jubatus/jubatus-installer/issues/35

Packaging tool must be updated too.

### PR DESCRIPTION
**Pull request by kmaehashi**
Fix #980

### CODE REVIEW

**Comment by kmaehashi** [comment]
@rimms Ok to review.

**Comment by rimms** [comment]
I tested RPM packaging tool (excute ``package.sh -cuai``) on CentOS 7.

The following error was occured:
```
Building package for mecab...
~/work/jubatus-1130/jubatus/tools/packaging/rpm/rpmbuild/mecab ~/work/jubatus-1130/jubatus/tools/packaging/rpm
~/work/jubatus-1130/jubatus/tools/packaging/rpm/rpmbuild/mecab/SOURCES ~/work/jubatus-1130/jubatus/tools/packaging/rpm/rpmbuild/mecab ~/work/jubatus-1130/jubatus/tools/packaging/rpm
Getting https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7cENtOXlicTFaRUE to ./uc?export=download&id=0B4y35FiV1wh7cENtOXlicTFaRUE
  ... snip ...
~/work/jubatus-1130/jubatus/tools/packaging/rpm/rpmbuild/mecab ~/work/jubatus-1130/jubatus/tools/packaging/rpm

error: File /path/to/work/jubatus-1130/jubatus/tools/packaging/rpm/rpmbuild/mecab/SOURCES/0B4y35FiV1wh7cENtOXlicTFaRUE: No such file or directory
```

**Comment by rimms** [comment]
I tested deb packaging tool (I excuted ``jubapkg -C -d -b -p deb``). It work correctly. 👍 

Travis works correctly:
https://travis-ci.org/jubatus/jubatus/builds/144392066

@kmaehashi Please fix RPM packaging tool.

**Comment by kmaehashi** [comment]
@rimms Thanks! fixed; I tested it on CentOS 6 and it worked.

BTW this is a technique used in https://fedoraproject.org/wiki/Packaging:SourceURL#Commit_Revision

**Comment by rimms** [comment]
I tested RPM packaging tool again. LGTM. 👍 

```
============================================================================================================================================
 Package                        Arch                  Version                      Repository                                          Size
============================================================================================================================================
Installing:
 mecab                          x86_64                0.996-1.el7                  /mecab-0.996-1.el7.x86_64                          767 k
 mecab-debuginfo                x86_64                0.996-1.el7                  /mecab-debuginfo-0.996-1.el7.x86_64                108 k
 mecab-devel                    x86_64                0.996-1.el7                  /mecab-devel-0.996-1.el7.x86_64                    1.7 M

Transaction Summary
============================================================================================================================================
Install  3 Packages

 .. snip ..

============================================================================================================================================
 Package                  Arch               Version                            Repository                                             Size
============================================================================================================================================
Installing:
 mecab-ipadic             x86_64             2.7.0.20070801-1.el7               /mecab-ipadic-2.7.0.20070801-1.el7.x86_64              51 M

Transaction Summary
============================================================================================================================================
Install  1 Package
```

**Pull request merged**
