### PR TITLE
Implement Python feature extraction bridge plug-in (#1197)

### PR DESCRIPTION
**Pull request by kmaehashi**
This implements feature proposed in #1197.

### CODE REVIEW

**Comment by kmaehashi** [comment]
# Design Document for Python Bridge

## Basic design of Python Bridge

The bridge directly uses Python [C/API](https://docs.python.org/3.1/c-api) to invoke feature extraction code written in Python.
When registering {string,binary,num}_type (on startup of Jubatus server), it instantiates a class that implements a feature extraction algorithm.
For each datum to process, the method of the instance is invoked with a datum record.
Python code extracts feature from the record and returns feature vectors.

The format of arguments and return values are different for each bridge interface.
They are precisely documented in headers.

Currently bridge interface for `string_feature`, `num_feature`, `binary_feature` and `word_splitter` are provided; filter/combination plugins are not yet supported (but they can easily be implemented).

## Detailed behaviors

Let's take an example.
The following is the simple Python code to extract features from binary data:

```python
class BinaryLengthExtractor(object):
    @classmethod
    def create(cls, param):
        return cls()

    def extract(self, key, value):
        return [("length_{0}".format(key), len(value))]
```

and the corresponding config will look like this:

```json
{ 
  "converter": {
    "binary_types": {
      "extract_length": {
        "method": "dynamic",
        "path": "libpython_bridge.so",
        "function": "binary_feature",
        "module": "binary_length",
        "class": "BinaryLengthExtractor"
      }
    },
    "binary_rules": [
      {
        "key": "*",
        "type": "extract_length"
      }
    ]
  }
}
```

In `binary_types` config:

* `function` specifies the bridge interface type and it can be one of `string_feature`, `num_feature`, `binary_feature` or `word_splitter`.
* `module` and `class` is a Python module name and class name.
  The module must be installed to the default module search path; you can use PYTHONPATH environment variable to add path.
* In addition, you can define extra parameters in the config dict.
  They are passed as an argument for `create` method as dict.

On startup, Jubatus does:

* Initializes Python interpreter and enable thread support.
* Adds "${JUBATUS_PLUGIN_DIR}/python" to `sys.path`.

For each Python-based `{string,num,binary}_types` registered, Jubatus does:

* Look for the module and class.
* Call `create` classmethod of the class.
  It should return a instance that actually implements the feature extraction algorithm.

For each datum that matches the rule arrived ("bridge"):

* Convert the input datum record (C++ data structure) as Python object.
* Call Python instance method with the arguments.
  It should return a result.
* Convert the returned result (Python object) to C++ data structure.

## How to build

This PR adds 2 configure options:

```
./waf configure --enable-python2
or
./waf configure --enable-python3
```

to enable Python bridge.

I have tested this PR with Python 2.7.3 and 3.5.1.

## Default library

As an example of Python bridge usage, it ships with 3 Python modules for feature extraction:

* space_splitter (`word_splitter`): Splits text with space (i.e., `space` rule implemented in Python)
* sentence_stemmer (`string_feature`): Splits the English sentence and then stem.
  This example requires [Natural Language Toolkit](http://www.nltk.org/) -- use `pip install nltk`.
* number_multiplier (`num_feature`): Multiply the input number by ``n``, where ``n`` is a parameter specified in config file.
* binary_length (`binary_feature`): Extracts length of binary record as a feature.

## Notes

Plugin directory structure is changed.
I separated plugin sources for each directory, as Python plugin consists of many files.

**Comment by kmaehashi** [comment]
## Workaroud for Python bug

There is a bug in Python that occur when embedding Python shared library into another shared library (like Jubatus plug-in).  As commented in the source code, here is a ticket for the bug: http://bugs.python.org/issue4434.  As far as I tested, this bug affects to Python 2.6 to present version of Python including 3.x series.

Without the workaround, you may see errors like this when importing `lib-dynload` libraries (e.g., datetime module):

```
ImportError: /usr/lib/python2.7/lib-dynload/_io.so: undefined symbol: PyExc_ImportError
```

c.f. https://stackoverflow.com/questions/11842920/undefined-symbol-pyexc-importerror-when-embedding-python-in-c

The workaround is to `dlopen` the Python shared library with `RTLD_GLOBAL` option, so that `lib-dynload`-ed libraries can find symbols defined in Python shared library.

**Comment by shiodat** [comment]
I made an original num_feature plugin and it works correctly :+1: 
https://gist.github.com/shiodat/f20972ba6298d4d8314d5eda460a98bd

The configure option ```--enable-python``` can be bit confusing and someone may think this option enables python-client.

I think ``--enable-python-plugin`` or ``--enable-pyplugin`` is better, what do you think?

**Comment by kmaehashi** [comment]
> The configure option --enable-python can be bit confusing and someone may think this option enables python-client.

I agree with that. I think `--enable-python-bridge` is better fits with existing options.
I also fixed `--use-python3` to `--enable-python3-bridge`.

**Comment by shiodat** [comment]
Good :+1:
I checked both `--enable-python-bridge` and `--enable-python3-bridge`.

**Comment by kmaehashi** [comment]
I found tiny typos in the source, directly fixed via e7ff8f34d78c6ec7cd1026499c1f7a95c1eb15cc and 2317c64b1059b5d08443a605f06d96f3e8d0f051.

**Pull request merged**
