### PR TITLE
Add man pages to RPM/DEB packages

### PR DESCRIPTION
**Pull request by kmaehashi**
Refs #1005

### CODE REVIEW

**Comment by kmaehashi** [comment]
Note for reviewer: I discovered that waf cannot install symbolik link files (which were previously generated by `regenerate.sh`), so I fixed to let waf create symbolic links in wscript.

**Comment by rimms** [comment]
Umm,.. I faced the following error.

```
error: File not found by glob: /path/to/jubatus/tools/packaging/rpm/rpmbuild/jubatus/BUILDROOT/jubatus-0.7.2-1.el7.x86_64/usr/share/man/man*/*
```

**Comment by kmaehashi** [comment]
@rimms To test this patch, you need to specify "add-man-to-pkg" branch in `package-config`.

https://github.com/jubatus/jubatus/blob/master/tools/packaging/rpm/package-config#L7

**Comment by kmaehashi** [comment]
More precisely, use

```
JUBATUS_CHECKOUT=add-man-to-pkg
JUBATUS_CORE_CHECKOUT=develop
```

for RPM, and use

```
JUBATUS_VER="add-man-to-pkg"
JUBATUS_CORE_VER="develop"
```

for DEB.

**Comment by rimms** [comment]
@kmaehashi Thanks!!

RPM:
```
$ which jubaclassifier
/usr/bin/jubaclassifier
$ man jubaclassifier
 .. snip ..
NAME
       jubatus_server - Jubatus Server

SYNOPSIS
          jubaclassifier [options ...]
          jubaanomaly [options ...]
          ...

DESCRIPTION
       Jubatus server provides the machine learning feature.
 .. snip..
$ export LANG=ja_JP.utf8
$ man jubaclassifier
 .. snip ..
NAME
       jubatus_server - Jubatus Server

SYNOPSIS
          jubaclassifier [options ...]
          jubaanomaly [options ...]
          ...

DESCRIPTION
       Jubatus サーバは機械学習の機能を提供する。
```

deb:
```
$ which jubaclassifier
/opt/jubatus/bin/jubaclassifier
$ man jubaclassifier
 .. snip ..
NAME
       jubatus_server - Jubatus Server

SYNOPSIS
          jubaclassifier [options ...]
          jubaanomaly [options ...]
          ...

DESCRIPTION
       Jubatus server provides the machine learning feature.
 .. snip..
$ export LANG=ja_JP.utf8
$ man jubaclassifier
 .. snip ..
NAME
       jubatus_server - Jubatus Server

SYNOPSIS
          jubaclassifier [options ...]
          jubaanomaly [options ...]
          ...

DESCRIPTION
       Jubatus サーバは機械学習の機能を提供する。
```

**Comment by rimms** [comment]
:+1:

**Pull request merged**
