### PR TITLE
wrong message `stopping mixer thread` on standalone mode

### LINKED ISSUE #916: "stopping mixer thread" log displayed in standalone mode
Even in the standalone mode, `stopping mixer thread` log is displayed when stopping server processes.

https://github.com/jubatus/jubatus/blob/0.6.6/jubatus/server/framework/server_helper.hpp#L264

This line must be inside the if clause.

### PR DESCRIPTION
**Pull request by kumagi**
Fix #916

### CODE REVIEW

**Comment by kmaehashi** [comment]
:+1:

**Comment by kmaehashi** [comment]
Ah, this was targeted to master... I'll revert.

**Comment by kmaehashi** [comment]
Reverted master, manually cherry-picked into develop.

**Comment by kumagi** [comment]
Thanks!

**Pull request merged**
