### PR TITLE
Fix the output of ORB

### PR DESCRIPTION
**Pull request by imaimai1125**
related to #1196

### CODE REVIEW

**Comment by TkrUdagawa** [comment]
For the reminder, I will summarize the ORB plugin.

1. Extract feature points by dense sampling.
That mean the plugin makes feature points like a grid.
2. Compute feature value for each feature point.
ORB plugin runs 256 tests for each feature point. Each test returns binary(0 or 1) value. Then the 256 bits of return values are the feature vector of that feature point.
3. Make Jubatus feature vector
push_back the vector with a pair (key: "`datum_key` # ORB / `feature_point_id` - `test_id`"  and value: `test result(0 or 1)`) (e.g. key: imge#ORB/0-0, value: 1).

**Comment by TkrUdagawa** [comment]
I think this PR is good enough for current ORB plugin output.

However, Jubatus can't fully utilize local features because most Jubatus algorithms use feature vector by each feature dimension and don't compare across dimensions.
In ORB case, Jubatus compares only the same coordinate point's features of two images.
And Jubatus can't find that an ORB feature is included in other places of another image.

We need to rethink about what image features fit Jubatus framework.

**Comment by TkrUdagawa** [comment]
:+1:

**Comment by kmaehashi** [comment]
I used BoVW when I tried SIFT in another project.
But maybe it will not sit well in current Jubatus architecture..

**Pull request merged**
